#[macro_use]
extern crate tracing;

#[macro_use]
pub mod macros;

mod about;
mod asn1;
mod common;
mod crypto_helper;
pub mod diff;
mod footer;
mod header;
mod jwt;
mod not_found;
pub mod serde;
mod url_query_params;
mod utils;

use about::About;
use asn1::Asn1ParserPage;
use crypto_helper::CryptoHelper;
use diff::DiffPage;
use footer::footer;
use header::Header;
use jwt::Jwt;
use not_found::not_found;
use wasm_bindgen::JsCast;
use wasm_bindgen::prelude::Closure;
use web_sys::window;
use yew::{Html, KeyboardEvent, function_component, html, use_effect, use_mut_ref};
use yew_agent::oneshot::OneshotProvider;
use yew_notifications::{Notification, NotificationFactory, NotificationsProvider};
use yew_router::{BrowserRouter, Routable, Switch};

use crate::diff::{DiffTask, JsonCodec};

#[derive(Clone, Routable, PartialEq)]
enum Route {
    #[at("/")]
    Home,
    #[at("/asn1")]
    Asn1Parser,
    #[at("/crypto-helper")]
    CryptoHelper,
    #[at("/jwt")]
    Jwt,
    #[at("/diff")]
    Diff,
    #[at("/about")]
    About,
    #[not_found]
    #[at("/404")]
    NotFound,
}

fn switch(routes: Route) -> Html {
    match routes {
        Route::Home => html! { <CryptoHelper /> },
        Route::Asn1Parser => html! { <Asn1ParserPage /> },
        Route::CryptoHelper => html! { <CryptoHelper /> },
        Route::Jwt => html! { <Jwt /> },
        Route::Diff => html! {
            // worker.js - will be autogenerated and placed in the root of the destination directory.
            <OneshotProvider<DiffTask, JsonCodec> path="worker.js">
                <DiffPage />
            </OneshotProvider<DiffTask, JsonCodec>>
        },
        Route::About => html! { <About /> },
        Route::NotFound => not_found(),
    }
}

#[function_component(App)]
pub fn app() -> Html {
    let component_creator = NotificationFactory;

    let keydown_closure = use_mut_ref(|| None::<Closure<dyn FnMut(KeyboardEvent)>>);
    let keyup_closure = use_mut_ref(|| None::<Closure<dyn FnMut(KeyboardEvent)>>);

    use_effect({
        let keydown_closure = keydown_closure.clone();
        let keyup_closure = keyup_closure.clone();

        move || {
            info!("Set ctrl-handler.");

            let document = window()
                .and_then(|w| w.document())
                .expect("Can not get document from window.");

            let keydown = Closure::<dyn FnMut(KeyboardEvent)>::new(move |e: KeyboardEvent| {
                let Some(document) = window().and_then(|w| w.document()) else {
                    warn!("Can not get document from window.");
                    return;
                };

                if e.ctrl_key()
                    && (e.code() == "ControlLeft" || e.key() == "Control")
                    && let Some(body) = document.body()
                    && let Err(err) = body.class_list().add_1("ctrl-down")
                {
                    error!(?err, "Can not add ctrl-down class to body.");
                }
            });

            document
                .add_event_listener_with_callback("keydown", keydown.as_ref().unchecked_ref())
                .expect("failed to add keydown event listener");

            let keyup = Closure::<dyn FnMut(KeyboardEvent)>::new(move |e: KeyboardEvent| {
                let Some(document) = window().and_then(|w| w.document()) else {
                    warn!("Can not get document from window.");
                    return;
                };

                if let Some(body) = document.body()
                    && !e.ctrl_key()
                    && let Err(err) = body.class_list().remove_1("ctrl-down")
                {
                    error!(?err, "Can not remove ctrl-down class from body.");
                }
            });

            document
                .add_event_listener_with_callback("keyup", keyup.as_ref().unchecked_ref())
                .expect("failed to add keyup event listener");

            *keydown_closure.borrow_mut() = Some(keydown);
            *keyup_closure.borrow_mut() = Some(keyup);

            move || {
                *keydown_closure.borrow_mut() = None;
                *keyup_closure.borrow_mut() = None;
            }
        }
    });

    html! {
        <BrowserRouter>
            <NotificationsProvider<Notification, NotificationFactory> {component_creator}>
                <div class="body">
                    <Header />
                    <Switch<Route> render={switch} />
                    {footer()}
                </div>
            </NotificationsProvider<Notification, NotificationFactory>>
        </BrowserRouter>
    }
}
